### ISSUE TITLE
Add social preview image

### ISSUE THREAD

**Issue by anki-code** [vaaaaanquish/xontrib-readable-traceback#6]
Hi! Thank you for the xontrib!

If you open [xontrib topic on Github](https://github.com/topics/xontrib) and scroll down you'll see the cute preview images for some xontribs. This is "Social preview" image that could be uploaded in the Settings of the repo.

Please take a common screenshot and put it to the preview image.

Thanks!

**Comment by vaaaaanquish** [comment]
@anki-code thanks!! I did it!!
